### PR TITLE
cmake: Set link_directiories()

### PR DESCRIPTION
**Pull request by cabelitos**
Otherwise this could break the compilation in systems
that the libraries are not installed in the default location

### CODE REVIEW

**Comment by jeanguyomarch** [comment]
Thank for the PR, but on this one I have a few remarks :-)
I can see it is the same issue than in https://github.com/jeanguyomarch/war2tools/pull/2 that needs to be fixed, but I think it should be handled differently this time.

war2tools is not compliant with cmake's good practises, so using `link_directories` was a good fix for this repository. war2edit, on the other hand, tries to do a bit better. I'vve read that `link_directory` should not be used, as stated in the documentation/recommandations:
- http://www.slideshare.net/DanielPfeifer1/cmake-48475415
- https://cmake.org/cmake/help/v3.0/command/link_directories.html

Instead, I think we should keep using exclusively the `target_link_libraries` but with different parameters. I've run some tests in a chroot with weird prefixes, and using `<LIB>_LDFLAGS` instead of `<LIB>_LIBRARIES` did the job (https://cmake.org/cmake/help/v3.0/module/FindPkgConfig.html).

So, (for bin/CMakeLists.txt), we would have:

``` cmake
target_link_libraries(war2edit
   ${EINA_LDFLAGS}
   ${EET_LDFLAGS}
   ${EVAS_LDFLAGS}
   ${ECORE_LDFLAGS}
   ${ECORE_FILE_LDFLAGS}
   ${ELEMENTARY_LDFLAGS}
   ${LIBPUD_LDFLAGS}
   ${LIBWAR2_LDFLAGS}
   ${CAIRO_LDFLAGS}
   ${LZMA_LDFLAGS}
)
```

What do you thing of this approach? If it seems right to you, I suggest you update your PR so I can merge it.

**Comment by cabelitos** [comment]
Hello @jeanguyomarch,

Your suggestion looks fine to me, however I was wondering. Should we also add the cflags?

I also would like to ask you what are the rules for a second PR? Should I close this one and open another or just push -f ?

**Comment by jeanguyomarch** [comment]
> I also would like to ask you what are the rules for a second PR?

In my github PR experience, you just `push -f` your branch. Github is smart enough to notice and will automatically update the PR :-)

> Should we also add the cflags?

The cflags returned by `pkg-config` are likely to be compiler-specific (i.e. gcc compatible). So, I don't think there is a convinient way to map the cflags from `pkg-config` to something that cmake would convert safely to any compiler. Also, cflags from EFL (and cairo as well) are pretty bad to me, as they are "raw" inclusion (`-I`). I prefer to do system inclusion for external libraries (i.e. with the `-isystem` flag), so my compilation does not get polluted by warnings from external headers (I use aggressive warning flags).

So my take on the cflags is to handle them manually, in a compiler-agnostic way.

That being said... we may introduce compiler-specific flags with the LDFLAGS thing. So after reflection, my proposition is not ideal either... maybe worse... If we have a weird LDFLAG, maybe `target_link_libraries` will fail.

So, I think I will take your original PR as it is. It is a simple solution to fix the build, in a compiler-independant manner. That's what matters to me right now. Maybe in the future `pkg_check_modules` will be dropped in favour of `find_package`, which may be the way to go. But that's build system pedantic issues. At least in a close future :-)

Does this make sense? I will let myself the night to think more about it, and if you are not opposed to this, I will merge the PR in its current state.

**Comment by cabelitos** [comment]
If LDFLAGS are going to mess around the build then I prefer to use link_directories(). But the final calls is yours.

Btw, I tried to reproduce the bug https://phab.enlightenment.org/T4624, however I was not able to.
Could you explain to me how to reproduce? 
I opened the window and resized it like a crazy and no crashes.

**Comment by jeanguyomarch** [comment]
For T4624, I can reproduce it easily when loading from a file. Due to a terrible hack (that I'm currently fixing :D) when I load a file, I open a new window to create a new editor (for an obscure reason of editors that were not resizable at some point). This allows to create a window resizing situation.

So, to reproduce:
0. if you don't have a map file: `wget http://war2.warcraft.org/files/terrain.pud`
1. open war2edit (no parameters)
2. select the open button
3. select the map from the fileselector (broken on Linux, works on my mac, T4686)
4. click Ok, confirm the Load, and move your mouse immediately.

**Comment by cabelitos** [comment]
Hey @jeanguyomarch,
Thank you for the details. I've fixed the problem. I will send a patch ASAP.

**Comment by cabelitos** [comment]
Take a look at https://phab.enlightenment.org/D4339 when you can!

**Comment by jeanguyomarch** [comment]
Very nice. Will test when I'll be back from work :-).
My mac is so slow to compile EFL I just can not dev on ecore_cocoa as I would like to... :/ Glad someone helps :-)

**Comment by jeanguyomarch** [comment]
Ok, this has been merged, thanks again :-)
For some reason, github did not automatically closed the thing... Souldn't have rebased...

Ref e9c88a9f38d3697141ee9d178c60ebbbdafffba4.

**Comment by cabelitos** [comment]
thanks :]

**Pull request closed without merging**
